### ISSUE TITLE
Test Icon theme in Apps

### ISSUE THREAD

**Issue by chekavy** [chekavy/cheser-icon-theme#13]
### Install Apps from Supported Packages file ###
* [x] abiword
* [x] abrt
* [x] adwaita-icon-theme
* [x] alacarte
* [x] almanah
* [x] anaconda
* [x] baobab
* [x] blender
* [x] cheese
* [x] dconf
* [x] deluge
* [x] devhelp
* [x] dia
* [x] dropbox
* [x] easytag
* [x] eog
* [x] evince
* [x] exfalso
* [x] fedora-logos
* [x] fedora-release-notes
* [x] file-roller
* [x] five-or-more
* [x] flash-player
* [x] four-in-a-row
* [x] geany
* [x] geany-plugins
* [x] geary
* [x] ghex
* [x] gimp
* [x] gitg
* [x] glade
* [x] gnome-abrt
* [x] gnome-boxes
* [x] gnome-calendar
* [x] gnome-chess
* [x] gnome-clocks
* [x] gnome-disk-utility
* [x] gnome-documents
* [x] gnome-icon-theme-extras
* [x] gnome-klotski
* [x] gnome-logs
* [x] gnome-mahjongg
* [x] gnome-mines
* [x] gnome-music
* [x] gnome-nettool
* [x] gnome-nibbles
* [x] gnome-online-accounts
* [x] gnome-photos
* [x] gnome-power-manager
* [x] gnome-robots
* [x] gnome-software
* [x] gnome-sound-recorder
* [x] gnome-sudoku
* [x] gnome-system-log
* [x] gnome-tetravex
* [x] gnome-tweak-tool
* [x] gnome-weather
* [x] gparted
* [x] gtk+
* [x] hitori
* [x] iagno
* [x] inkscape
* [x] keepassx
* [x] leafpad
* [x] libpeas
* [x] lightsoff
* [x] liveusb-creator
* [x] meld
* [x] nemiver
* [x] orca
* [x] polari
* [x] quadrapassel
* [x] remmina
* [x] rhythmbox
* [x] seahorse
* [x] shotwell
* [x] sound-juicer
* [x] swell-foop
* [x] tali
* [x] totem
* [x] tracker
* [x] transmission
* [x] vinagre
* [x] virt-viewer
* [x] xchat
* [x] yelp
* [x] yelp-xsl
* [x] yumex

**Comment by sljunkie** [comment]
deluge OK
brasero's progress/status icons have now the sizes 16x16 22x22 24x24 32x32 and scalable (in svg format)
tracker OK
yelp/yelp-xsl OK
sound-juicer OK
shotwell OK
seahorse OK
vinagre OK
tali OK
swell-foop OK
quadrapassel OK
polari OK
orca OK
hitori OK
nemiver OK
dia OK

**Comment by sljunkie** [comment]
exfalso could be left with its original icon, because many distributions will package it along quodlibet which has an icon style that matches exfalso's.

**Comment by chekavy** [comment]
> deluge OK
> brasero's progress/status icons have now the sizes 16x16 22x22 24x24 32x32 and scalable (in svg format)
> tracker OK
> yelp/yelp-xsl OK
> sound-juicer OK
> shotwell OK
> seahorse OK
> vinagre OK
> tali OK
> swell-foop OK
> quadrapassel OK
> polari OK
> orca OK
> hitori OK
> nemiver OK
> dia OK

Thanks!

**Comment by chekavy** [comment]
> exfalso could be left with its original icon, because many distributions will package it along quodlibet which has an icon style that matches exfalso's.

I think, that exfalso icon is OK.
