### ISSUE TITLE
folder-publicshare looks off

### ISSUE THREAD

**Issue by chpii** [chekavy/cheser-icon-theme#18]
![folder-publicshare](https://raw.githubusercontent.com/chekavy/cheser-icon-theme/master/Cheser/256x256/places/folder-publicshare.png)![folder-music](https://raw.githubusercontent.com/chekavy/cheser-icon-theme/master/Cheser/256x256/places/folder-music.png)
![folder-publicshare](https://git.gnome.org/browse/adwaita-icon-theme/plain/Adwaita/256x256/places/folder-publicshare.png)![folder-music](https://git.gnome.org/browse/adwaita-icon-theme/plain/Adwaita/256x256/places/folder-music.png)
First icon uses bolder lines and occupies much more space vertically than other folder icons.

**Comment by chpii** [comment]
If you really want to use that symbol It should be done as outline like the one on folder-music icon.

**Comment by chekavy** [comment]
Иконка 'folder-publicshare' - это просто объединенные иконки 'folder' и 'emblem-shared'
![folder](https://raw.githubusercontent.com/chekavy/cheser-icon-theme/master/Cheser/256x256/places/folder.png) ![emblem-shared](https://raw.githubusercontent.com/chekavy/cheser-icon-theme/master/Cheser/256x256/emblems/emblem-shared.png)
