### ISSUE TITLE
increase performance

### ISSUE THREAD

**Issue by sixsixfive** [chekavy/cheser-icon-theme#21]
Please optimize your icons:

for exampe run something like "optipng -nx -strip all $PNG" for all you pngs for the svgs you can use svg-cleaner(https://github.com/RazrFalcon/SVGCleaner) to remove useles stuff like comments & metadata, you should also generate a icon-cache (gtk-update-icon-cache) to impove gtk2 performance

cheers

**Comment by chekavy** [comment]
I'll see what I can do.
