### ISSUE TITLE
[Mimetypes] Bigger mimetypes sizes

### ISSUE THREAD

**Issue by sljunkie** [chekavy/cheser-icon-theme#31]
![screenshot from 2015-04-13 15-55-56](https://cloud.githubusercontent.com/assets/7532854/7123043/c70a2244-e1f5-11e4-8213-d77a552c746e.png)
![screenshot from 2015-04-13 15-55-19](https://cloud.githubusercontent.com/assets/7532854/7123044/c73d6f50-e1f5-11e4-9174-639796736e20.png)

Mimetypes (especially code-related) that that came from gnome-colors need to be reworked from the old 'cartoonish' style and get bigger sizes; I'm using nautilus 3.16.0 in those screenshots.

**Comment by chekavy** [comment]
I'll see what I can do.

**Comment by chekavy** [comment]
@sljunkie 

I'm working on mimetypes icons in the issue #8.
