### ISSUE TITLE
Remove the same with upstream icons

### ISSUE THREAD

**Issue by chekavy** [chekavy/cheser-icon-theme#48]
* [x] abiword-3.0.1
* [x] abrt-2.5.0
* [x] aisleriot-3.16.2
* [x] anaconda-22
* [x] authconfig-6.2.10
* [x] baobab-3.16.1
* [x] blender-2.74
* [x] brasero-3.12.1
* [x] cheese-3.16.1
* [x] devassistant-0.10.3
* [x] devhelp-3.16.1
* [x] dia-0.97.3
* [x] ekiga-4.0.1
* [x] empathy-3.12.10
* [x] eog-3.16.2
* [x] evince-3.16.1
* [x] evolution-3.16.1
* [x] fedora-logos-21.0.5
* [x] fedora-release-notes-22
* [x] gcr-3.16.0
* [x] geary-0.10.0
* [x] geocode-glib-3.16.0
* [x] ghex-3.10.1
* [x] gitg-3.16.0
* [x] glade-3.18.3
* [x] gnome-abrt-1.1.0
* [x] gnome-bluetooth-3.16.0
* [x] gnome-boxes-3.16.2
* [x] gnome-builder-3.16.1
* [x] gnome-calendar-3.16.0
* [x] gnome-characters-3.16.0
* [x] gnome-chess-3.16.2
* [x] gnome-clocks-3.16.1
* [x] gnome-color-manager-3.16.0
* [x] gnome-control-center-3.16.0
* [x] gnome-disk-utility-3.16.2
* [x] gnome-documents-3.16.0
* [x] gnome-icon-theme-extras-3.12.0
* [x] gnome-klotski-3.16.1
* [x] gnome-logs-3.16.1
* [x] gnome-mahjongg-3.16.1
* [x] gnome-maps-3.16.1
* [x] gnome-mines-3.16.1
* [x] gnome-music-3.16.0
* [x] gnome-nettool-3.8.1
* [x] gnome-nibbles-3.16.1
* [x] gnome-phone-manager-0.69
* [x] gnome-photos-3.16.0
* [x] gnome-power-manager-3.16.1
* [x] gnome-robots-3.16.1
* [x] gnome-software-3.16.0
* [x] gnome-sound-recorder-3.16.0
* [x] gnome-sudoku-3.16.0
* [x] gnome-weather-3.16.2.1
* [x] gnote-3.16.0
* [x] gnumeric-1.12.21
* [x] haguichi-1.0.26
* [x] hamster-time-tracker-1.04
* [x] hitori-3.16.1
* [x] iagno-3.16.0
* [x] im-chooser-1.6.4
* [x] mplayer-1.1.1
* [x] nemiver-0.9.5
* [x] office-runner-1.0.2
* [x] orca-3.16.2
* [x] pdfmod-0.9.1
* [x] pitivi-0.94
* [x] polari-3.16.0
* [x] quadrapassel-3.16.1
* [x] seahorse-3.16.0
* [x] shotwell-0.22.0
* [x] simple-scan-3.16.0
* [x] sound-juicer-3.16.0
* [x] swell-foop-3.16.1
* [x] system-config-date-1.10.7
* [x] system-config-httpd-1.5.5
* [x] system-config-nfs-1.4.2
* [x] system-config-samba-1.2.100
* [x] tomboy-1.15.4
* [x] totem-3.16.2
* [x] tracker-1.4.0
* [x] virt-manager-1.1.0
* [x] xarchiver-0.5.4
* [x] xchat-2.8.8
* [x] xfce4-power-manager-1.4.4
* [x] yelp-3.16.0

**Comment by ztefn** [comment]
Please remove all app and status icons for haguichi too, they are the same with upstream prior to version [1.0.25](https://www.haguichi.net/news/release1025/), thus overriding the current upstream icons with these older ones. Also, since version [1.3.0](https://www.haguichi.net/news/release130/) it has a new logo and the node icons have different sizes, which makes it look quite crappy using cheser icon theme.

**Comment by chekavy** [comment]
> Please remove all app and status icons for haguichi too, they are the same with upstream prior to version 1.0.25, thus overriding the current upstream icons with these older ones. Also, since version 1.3.0 it has a new logo and the node icons have different sizes, which makes it look quite crappy using cheser icon theme.

Done. See ad85b75 commit.
